name: mybinder #name of your env
channels:
        - conda-forge
dependencies:
        - python=3.7
        - numpy
        - netCDF4
        - matplotlib
        - cartopy
        - xarray
        - ipython
        - pandas
        - seaborn
        - dask
        - nc-time-axis
        - jupyterlab
        - ipympl
        - nodejs
        - pooch #needed to download data
